version: "3.9"

services:
  dove_listener:
    build: .
    container_name: dove_listener
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    devices:
      - "/dev/snd:/dev/snd"




